### ISSUE TITLE
Úkol 1 je hotový

### ISSUE THREAD

**Issue by hepsik** [hepsik/python-042023#1]
@AnetaPopelova Prosím o kontrolu :) Díky

**Comment by AnetaPopelova** [comment]
Pisu sem sve dojmy (i drobnosti):

- Tady `data[data["rank"] == 1.0]` nemusi byt 1.0, staci 1. Hodnota je cislo, to jen notebook nam to ukazuji i s jednim desetinnym mistem.

> Sám se mi sloupec state nastavil jako index

To se deje pri pouziti `groupby`. [Tady](https://www.geeksforgeeks.org/how-to-reset-index-after-groupby-pandas/) k tomu neco je. Podle [dokumentace](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html) muzes u `groupby` pouzit parameter `as_index = False`. 

- `data[(data["rank"] == 1.0) | (data["rank"] == 2.0)]` jde zjednodusit na .isin([1, 2])

Mas to moc hezky, spravne a ciste vyresene 👍
