### ISSUE TITLE
Úkol 3

### ISSUE THREAD

**Issue by hepsik** [hepsik/python-042023#3]
Úkol 3 je hotový.
@AnetaPopelova

**Comment by AnetaPopelova** [comment]
Máš to velmi hezky zpracované včetně interpretací. 

Sepíšu jen pár dojmů:
- importy modulů patří v notebooku ideálně všechny nahoru. Pro zajímavost, existuje na to i [předepsané pořadí](https://stackoverflow.com/questions/20762662/whats-the-correct-way-to-sort-python-import-x-and-from-x-import-y-statement). 
- z lekce jsi převzala i kus kódu `data = data[data["Expectancy_zscore"]<3]`, kterým jsme řešili outliers. Ten tu není potřeba, mužeš si vyzkoušet, že s hodnotou, kteroujsi použila to výsledek nijak nemění

👍
